# Generated by Django 4.0.5 on 2022-06-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_historicalmeasureunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='made_by',
            field=models.CharField(max_length=50, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nombre del farmaco'),
        ),
        migrations.AlterField(
            model_name='product',
            name='made_by',
            field=models.CharField(max_length=50, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre del farmaco'),
        ),
    ]
