# Generated by Django 4.0.5 on 2022-06-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_historicalproduct_made_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='grammage',
            field=models.FloatField(verbose_name='Gramaje'),
        ),
        migrations.AlterField(
            model_name='product',
            name='grammage',
            field=models.FloatField(verbose_name='Gramaje'),
        ),
    ]
